/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PruefungenRouteImport } from './routes/pruefungen'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BenutzerRouteImport } from './routes/benutzer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PruefungenIndexRouteImport } from './routes/pruefungen.index'
import { Route as PruefungenIdRouteImport } from './routes/pruefungen.$id'
import { Route as BewertungenIdRouteImport } from './routes/bewertungen.$id'

const PruefungenRoute = PruefungenRouteImport.update({
  id: '/pruefungen',
  path: '/pruefungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BenutzerRoute = BenutzerRouteImport.update({
  id: '/benutzer',
  path: '/benutzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungenIndexRoute = PruefungenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PruefungenRoute,
} as any)
const PruefungenIdRoute = PruefungenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PruefungenRoute,
} as any)
const BewertungenIdRoute = BewertungenIdRouteImport.update({
  id: '/bewertungen/$id',
  path: '/bewertungen/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benutzer': typeof BenutzerRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/pruefungen': typeof PruefungenRouteWithChildren
  '/bewertungen/$id': typeof BewertungenIdRoute
  '/pruefungen/$id': typeof PruefungenIdRoute
  '/pruefungen/': typeof PruefungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benutzer': typeof BenutzerRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/bewertungen/$id': typeof BewertungenIdRoute
  '/pruefungen/$id': typeof PruefungenIdRoute
  '/pruefungen': typeof PruefungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benutzer': typeof BenutzerRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/pruefungen': typeof PruefungenRouteWithChildren
  '/bewertungen/$id': typeof BewertungenIdRoute
  '/pruefungen/$id': typeof PruefungenIdRoute
  '/pruefungen/': typeof PruefungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benutzer'
    | '/docs'
    | '/login'
    | '/profil'
    | '/pruefungen'
    | '/bewertungen/$id'
    | '/pruefungen/$id'
    | '/pruefungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benutzer'
    | '/docs'
    | '/login'
    | '/profil'
    | '/bewertungen/$id'
    | '/pruefungen/$id'
    | '/pruefungen'
  id:
    | '__root__'
    | '/'
    | '/benutzer'
    | '/docs'
    | '/login'
    | '/profil'
    | '/pruefungen'
    | '/bewertungen/$id'
    | '/pruefungen/$id'
    | '/pruefungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenutzerRoute: typeof BenutzerRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  PruefungenRoute: typeof PruefungenRouteWithChildren
  BewertungenIdRoute: typeof BewertungenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pruefungen': {
      id: '/pruefungen'
      path: '/pruefungen'
      fullPath: '/pruefungen'
      preLoaderRoute: typeof PruefungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benutzer': {
      id: '/benutzer'
      path: '/benutzer'
      fullPath: '/benutzer'
      preLoaderRoute: typeof BenutzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefungen/': {
      id: '/pruefungen/'
      path: '/'
      fullPath: '/pruefungen/'
      preLoaderRoute: typeof PruefungenIndexRouteImport
      parentRoute: typeof PruefungenRoute
    }
    '/pruefungen/$id': {
      id: '/pruefungen/$id'
      path: '/$id'
      fullPath: '/pruefungen/$id'
      preLoaderRoute: typeof PruefungenIdRouteImport
      parentRoute: typeof PruefungenRoute
    }
    '/bewertungen/$id': {
      id: '/bewertungen/$id'
      path: '/bewertungen/$id'
      fullPath: '/bewertungen/$id'
      preLoaderRoute: typeof BewertungenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PruefungenRouteChildren {
  PruefungenIdRoute: typeof PruefungenIdRoute
  PruefungenIndexRoute: typeof PruefungenIndexRoute
}

const PruefungenRouteChildren: PruefungenRouteChildren = {
  PruefungenIdRoute: PruefungenIdRoute,
  PruefungenIndexRoute: PruefungenIndexRoute,
}

const PruefungenRouteWithChildren = PruefungenRoute._addFileChildren(
  PruefungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenutzerRoute: BenutzerRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  PruefungenRoute: PruefungenRouteWithChildren,
  BewertungenIdRoute: BewertungenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
